//! `rac retrieve` conformance: replay `retrieve.json` (generated by the
//! ORACLE-NEXT oracle, `rac.services.retrieve` @ 0.1.dev55+gf2091befd, over
//! the live `rac/` corpus and the `rust/fixtures/retrieve/` corpora) and
//! assert BYTE equality on both the budget-capped serialization (the
//! `--json` payload) and the human rendering.
//!
//! REGENERABLE — any change to `rac/` or the fixtures shifts the vectors;
//! rerun `rust/spec/gen_vectors_retrieve.py` with the oracle-next venv.

use std::fs;
use std::path::Path;

use rac_engine::output::render_retrieve_human;
use rac_engine::budget::serialize;
use rac_engine::derived::{build_derived_index, SCHEMA_VERSION};
use rac_engine::index_store::{corpus_content_hash, open_store, write_store};
use rac_engine::retrieve::{
    retrieve_grounding, retrieve_grounding_from_derived, retrieve_grounding_from_store,
};
use serde_json::Value;

fn vectors() -> Value {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/vectors/retrieve.json");
    let text = fs::read_to_string(&path).expect("read retrieve.json");
    serde_json::from_str(&text).expect("parse retrieve.json")
}

/// The corpus paths in the vectors are relative to the repo root; run the
/// whole suite from there (one test fn, so no cwd races between threads).
fn enter_repo_root() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("canonicalize repo root");
    std::env::set_current_dir(&root).expect("chdir to repo root");
}

#[test]
fn retrieve_payloads_match_oracle_next() {
    enter_repo_root();
    let data = vectors();
    let cases = data["cases"].as_array().expect("cases array");
    assert_eq!(cases.len() as i64, data["case_count"].as_i64().unwrap());
    for case in cases {
        let directory = case["directory"].as_str().unwrap();
        let task = case["task"].as_str().unwrap();
        let scope = case["scope"].as_str();
        let top_k = case["top_k"].as_i64().unwrap();
        let budget = case["budget"].as_i64().unwrap();
        let live_only = case["live_only"].as_bool().unwrap();
        let label = format!(
            "dir={directory} task={task:?} scope={scope:?} top_k={top_k} \
             budget={budget} live_only={live_only}"
        );

        let payload = retrieve_grounding(directory, task, scope, top_k, budget, live_only);
        let serialized = serialize(&payload, budget);
        assert_eq!(
            serialized,
            case["serialized"].as_str().unwrap(),
            "serialized JSON diverged: {label}"
        );

        let truncated: Value = serde_json::from_str(&serialized).expect("valid JSON");
        assert_eq!(
            render_retrieve_human(&truncated),
            case["human"].as_str().unwrap(),
            "human rendering diverged: {label}"
        );
    }
}

#[test]
fn fresh_snapshot_and_mapped_grounding_are_identical() {
    enter_repo_root();
    let data = vectors();
    let cases = data["cases"].as_array().expect("cases array");
    let directories: std::collections::BTreeSet<&str> = cases
        .iter()
        .map(|case| case["directory"].as_str().unwrap())
        .collect();

    for (directory_index, directory) in directories.into_iter().enumerate() {
        let derived = build_derived_index(directory, true);
        let corpus_hash = corpus_content_hash(directory, true);
        let cache = std::env::temp_dir().join(format!(
            "rac-grounding-model-{}-{directory_index}",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&cache);
        assert!(write_store(&cache, &corpus_hash, SCHEMA_VERSION, &derived));
        let reader =
            open_store(&cache, &corpus_hash, SCHEMA_VERSION).expect("open grounding store");

        for case in cases
            .iter()
            .filter(|case| case["directory"].as_str() == Some(directory))
        {
            let task = case["task"].as_str().unwrap();
            let scope = case["scope"].as_str();
            let top_k = case["top_k"].as_i64().unwrap();
            let budget = case["budget"].as_i64().unwrap();
            let live_only = case["live_only"].as_bool().unwrap();
            let fresh = retrieve_grounding(directory, task, scope, top_k, budget, live_only);
            let snapshot = retrieve_grounding_from_derived(
                directory, task, scope, top_k, budget, live_only, &derived,
            );
            let mapped = retrieve_grounding_from_store(
                directory, task, scope, top_k, budget, live_only, &reader,
            );
            let label = format!("dir={directory} task={task:?} scope={scope:?}");
            assert_eq!(snapshot, fresh, "snapshot mismatch: {label}");
            assert_eq!(mapped, fresh, "mapped mismatch: {label}");
        }
        drop(reader);
        let _ = fs::remove_dir_all(&cache);
    }
}
