//! `rac retrieve` conformance: replay `retrieve.json` (generated by the
//! ORACLE-NEXT oracle, `rac.services.retrieve` @ 0.1.dev55+gf2091befd, over
//! the frozen corpus snapshot `rust/fixtures/corpus` and the
//! `rust/fixtures/retrieve/` corpora, COUNCIL-REVIEW B3) and assert BYTE
//! equality on both the budget-capped serialization (the `--json` payload)
//! and the human rendering.
//!
//! The snapshot decouples the corpus cases from live `rac/` edits. Regenerate
//! after a *snapshot* edit with the oracle-next venv:
//! `rust/spec/gen_vectors_retrieve.py`.

use std::fs;
use std::path::Path;

use rac_engine::output::render_retrieve_human;
use rac_engine::budget::serialize;
use rac_engine::retrieve::retrieve_grounding;
use serde_json::Value;

fn vectors() -> Value {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/vectors/retrieve.json");
    let text = fs::read_to_string(&path).expect("read retrieve.json");
    serde_json::from_str(&text).expect("parse retrieve.json")
}

/// Snapshot-rooted cases (COUNCIL-REVIEW B3: `rac/`, `tests/fixtures/resolve`)
/// replay from the frozen corpus root so their paths tokenize as the live tree;
/// the already-frozen `rust/fixtures/retrieve/*` fixtures replay from the repo
/// root. Both resolve from `CARGO_MANIFEST_DIR` (rust/rac-engine). One test fn,
/// so the per-case chdir has no cwd race between threads.
fn chdir_for(corpus_root: bool) {
    let rel = if corpus_root { "../fixtures/corpus" } else { "../.." };
    let root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join(rel)
        .canonicalize()
        .expect("canonicalize case root");
    std::env::set_current_dir(&root).expect("chdir to case root");
}

#[test]
fn retrieve_payloads_match_oracle_next() {
    let data = vectors();
    let cases = data["cases"].as_array().expect("cases array");
    assert_eq!(cases.len() as i64, data["case_count"].as_i64().unwrap());
    for case in cases {
        // Every case must carry the flag; defaulting a missing flag to `false`
        // would silently read the LIVE repo root the snapshot exists to replace.
        chdir_for(
            case["corpus_root"]
                .as_bool()
                .expect("each retrieve case carries a corpus_root flag"),
        );
        let directory = case["directory"].as_str().unwrap();
        let task = case["task"].as_str().unwrap();
        let scope = case["scope"].as_str();
        let top_k = case["top_k"].as_i64().unwrap();
        let budget = case["budget"].as_i64().unwrap();
        let live_only = case["live_only"].as_bool().unwrap();
        let label = format!(
            "dir={directory} task={task:?} scope={scope:?} top_k={top_k} \
             budget={budget} live_only={live_only}"
        );

        let payload = retrieve_grounding(directory, task, scope, top_k, budget, live_only);
        let serialized = serialize(&payload, budget);
        assert_eq!(
            serialized,
            case["serialized"].as_str().unwrap(),
            "serialized JSON diverged: {label}"
        );

        let truncated: Value = serde_json::from_str(&serialized).expect("valid JSON");
        assert_eq!(
            render_retrieve_human(&truncated),
            case["human"].as_str().unwrap(),
            "human rendering diverged: {label}"
        );
    }
}
