//! Oracle-vector conformance tests for `rac_engine::validate`.
//!
//! Vectors: tests/vectors/validate.json — every .md under the frozen corpus
//! snapshot rust/fixtures/corpus/{rac,tests} (COUNCIL-REVIEW B3), generated by
//! rust/spec/gen_vectors_validate.py. Decoupled from live corpus *content*
//! edits. Caveat: the `product` cases apply repo config via validate_product,
//! whose walk-up finds no .rac/config.yaml inside the snapshot and so resolves
//! the repo-root .rac/config.yaml (the same stanza the oracle sees) — so a
//! change to *that config* still requires regenerating these vectors. (A frozen
//! config inside the snapshot can't fix this without moving retrieve's
//! nearest-.rac/config.yaml scope anchor off the repo root; left as a follow-up.)
//! Three configurations replay byte-exactly:
//! - bare:    validate(product)
//! - github:  validate(product, ticketing_provider="github")
//! - product: validate_product(product, start=<parent>) (repo config applied)

use rac_engine::parse::{parse_file, Issue};
use rac_engine::validate::{validate, validate_product};
use serde_json::{json, Value};

const VECTORS: &str = include_str!("vectors/validate.json");

/// The vectors carry "rac/..."/"tests/..." paths into the frozen snapshot
/// (COUNCIL-REVIEW B3); read them — and resolve `validate_product`'s config
/// walk-up — from the snapshot root. One test fn, so no cwd race.
fn enter_corpus_root() {
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../fixtures/corpus")
        .canonicalize()
        .expect("canonicalize frozen corpus root");
    std::env::set_current_dir(&root).expect("chdir to frozen corpus root");
}

fn issue_rows(issues: &[Issue]) -> Value {
    Value::Array(
        issues
            .iter()
            .map(|i| json!([i.severity, i.code, i.message, i.line]))
            .collect(),
    )
}

fn parent(path: &str) -> String {
    match path.rfind('/') {
        Some(0) => "/".to_string(),
        Some(i) => path[..i].to_string(),
        None => ".".to_string(),
    }
}

#[test]
fn validate_matches_oracle() {
    enter_corpus_root();
    let root: Value = serde_json::from_str(VECTORS).expect("vectors parse");
    let cases = root["cases"].as_array().expect("cases");
    assert!(!cases.is_empty());
    for case in cases {
        let path = case["path"].as_str().unwrap();
        let artifact = parse_file(path);

        assert_eq!(
            issue_rows(&validate(&artifact, None, None)),
            case["bare"],
            "{path}: bare validate"
        );
        assert_eq!(
            issue_rows(&validate(&artifact, Some("github"), None)),
            case["github"],
            "{path}: github-provider validate"
        );
        assert_eq!(
            issue_rows(&validate_product(&artifact, &parent(path))),
            case["product"],
            "{path}: validate_product"
        );
    }
}
